### PR TITLE
Provide devworkspace support, upgraded Quarkus version to 2.7.1.Final

### PR DESCRIPTION
**Pull request by dkwon17**
Related issue: https://github.com/eclipse/che/issues/20090

This PR provides devworkspaces support by:
* removing `che.machine.token` and `che.api.internal` config 
* reading devworkspace info via kubernetes client (fabric8)
* retrieving username via `/config/user/profile/name` file

TODO: need to fix integration and native mode tests

### CODE REVIEW

**Review by ibuziuk — COMMENTED** [review]
@dkwon17 could you please take a look why CI is failing?

**Comment by dkwon17** [comment]
@ibuziuk It is a problem with how the openapi schema is generated, I will work on a fix

**Review by ibuziuk — APPROVED** [review]
great job :+1:

**Comment by dkwon17** [comment]
Thank you @ibuziuk, I have made some changes to the native integration tests and updated the readme. This PR can be merged IMO.

**Pull request merged**
