### PR TITLE
fix: Remove untrusted forked moxios and just use jest

### PR DESCRIPTION
**Pull request by benoitf**
project is using a forked moxios so we should stick to official moxios but using moxios also looks overcomplicated while we can just use jest mocking

Also bump dependencies

### CODE REVIEW

**Comment by benoitf** [comment]
ok I got extra problems with the CI that was using nodejs 10 ! bump it to 12 (knowing that current LTS is now nodejs 16)

**Review by ibuziuk — APPROVED** [review]
@benoitf thank you for the contribution :+1:

**Comment by benoitf** [comment]
it seems there is a typescript definition missing

**Comment by benoitf** [comment]
> Error: @eclipse-che/theia-remote-impl-che-server: [compile] src/node/che-server-telemetry-service-impl.ts(11,48): error TS7016: Could not find a declaration file for module '@eclipse-che/workspace-telemetry-client'. '/home/runner/work/che-theia/che-theia/node_modules/@eclipse-che/workspace-telemetry-client/dist/server.js' implicitly has an 'any' type.

investigating...

**Pull request merged**
